create table if not exists public.visitantes_cotizacion (
  id uuid primary key,
  cliente_id text,
  creado_en timestamptz not null default now(),
  ultima_actividad timestamptz not null default now()
);

create table if not exists public.visitas_cotizacion (
  id bigint generated by default as identity primary key,
  propuesta_id text not null,
  vendedor_id uuid not null,
  visitante_id uuid not null references public.visitantes_cotizacion(id) on delete cascade,
  visitada_en timestamptz not null default now(),
  significativa boolean not null default true
);

create index if not exists visitas_cotizacion_propuesta_fecha_idx
  on public.visitas_cotizacion (propuesta_id, visitada_en desc);
create index if not exists visitas_cotizacion_vendedor_fecha_idx
  on public.visitas_cotizacion (vendedor_id, visitada_en desc);
create index if not exists visitas_cotizacion_visitante_fecha_idx
  on public.visitas_cotizacion (visitante_id, propuesta_id, visitada_en desc);

alter table public.visitantes_cotizacion enable row level security;
alter table public.visitas_cotizacion enable row level security;

drop policy if exists "Vendedores leen visitas propias" on public.visitas_cotizacion;
create policy "Vendedores leen visitas propias"
  on public.visitas_cotizacion
  for select
  to authenticated
  using (vendedor_id = auth.uid());

create or replace function public.registrar_visita_cotizacion(
  p_propuesta_id text,
  p_visitante_id uuid,
  p_debounce_minutos integer default 30
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  vendedor uuid;
  ultima_significativa timestamptz;
  fecha_actual timestamptz := now();
  es_significativa boolean;
  visita_creada bigint;
  total_visitas integer;
  debounce_seguro integer := greatest(5, least(coalesce(p_debounce_minutos, 30), 1440));
begin
  select user_id into vendedor
  from public.propuestas
  where datos #>> '{propuesta,id}' = p_propuesta_id
  limit 1;

  if vendedor is null then
    return jsonb_build_object('registrada', false);
  end if;

  insert into public.visitantes_cotizacion (id, ultima_actividad)
  values (p_visitante_id, fecha_actual)
  on conflict (id) do update
    set ultima_actividad = excluded.ultima_actividad;

  select max(visitada_en) into ultima_significativa
  from public.visitas_cotizacion
  where propuesta_id = p_propuesta_id
    and visitante_id = p_visitante_id
    and significativa = true;

  es_significativa := ultima_significativa is null
    or ultima_significativa <= fecha_actual - make_interval(mins => debounce_seguro);

  insert into public.visitas_cotizacion (
    propuesta_id,
    vendedor_id,
    visitante_id,
    visitada_en,
    significativa
  ) values (
    p_propuesta_id,
    vendedor,
    p_visitante_id,
    fecha_actual,
    es_significativa
  ) returning id into visita_creada;

  update public.propuestas
  set datos = jsonb_set(
    jsonb_set(
      jsonb_set(datos, '{propuesta,aperturas}', to_jsonb(coalesce((datos #>> '{propuesta,aperturas}')::integer, 0) + 1), true),
      '{propuesta,primeraApertura}', coalesce(datos #> '{propuesta,primeraApertura}', to_jsonb(fecha_actual)), true
    ),
    '{propuesta,ultimaApertura}', to_jsonb(fecha_actual), true
  )
  where datos #>> '{propuesta,id}' = p_propuesta_id;

  select count(*)::integer into total_visitas
  from public.visitas_cotizacion
  where propuesta_id = p_propuesta_id;

  return jsonb_build_object(
    'registrada', true,
    'visita_id', visita_creada,
    'significativa', es_significativa,
    'visitada_en', fecha_actual,
    'total_visitas', total_visitas
  );
end;
$$;

revoke all on function public.registrar_visita_cotizacion(text, uuid, integer) from public;
grant execute on function public.registrar_visita_cotizacion(text, uuid, integer) to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.visitas_cotizacion;
exception
  when duplicate_object then null;
end;
$$;
